FROM amazonlinux:2023

# 기본 패키지 설치
RUN dnf update -y
RUN dnf install -y python3.12 python3.12-pip python3.12-devel gcc

# 작업 디렉토리 설정
WORKDIR /app

# 파이썬 패키지 설치
COPY requirements.txt .
RUN pip3.12 install --no-cache-dir --upgrade pip
RUN pip3.12 install --no-cache-dir -r requirements.txt

# 앱 코드 복사
COPY . .

EXPOSE 8080
CMD ["python3.12", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]